In [2]:
import pandas as pd

## Series

In [9]:
import numpy as np
arr = np.arange(100,110)
print(arr)

[100 101 102 103 104 105 106 107 108 109]


In [10]:
s = pd.Series(arr)
print(s)

0    100
1    101
2    102
3    103
4    104
5    105
6    106
7    107
8    108
9    109
dtype: int64


In [12]:
s = pd.Series(arr,dtype='int32')
print(s)

0    100
1    101
2    102
3    103
4    104
5    105
6    106
7    107
8    108
9    109
dtype: int32


In [15]:
person = ['kim', 'lee', 'park', 'hong'] 
s = pd.Series(person)
print(s)

0     kim
1     lee
2    park
3    hong
dtype: object


In [16]:
s = pd.Series([1, 2, 3, 4, 5, '99'])
print(s)

0     1
1     2
2     3
3     4
4     5
5    99
dtype: object


## indexing

In [17]:
person = ['kim', 'lee', 'park', 'hong' ]
s = pd.Series(person)

In [18]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [21]:
s[2]    # 시리즈에서 음수 인덱싱은 불가능!

'park'

In [26]:
s = pd.Series(person, index = ['a','b','c','d'])
s = pd.Series(person, index = list('abcd'))
print(s)

a     kim
b     lee
c    park
d    hong
dtype: object


In [27]:
s['a']

'kim'

In [29]:
s.values

array(['kim', 'lee', 'park', 'hong'], dtype=object)

In [30]:
s.ndim

1

In [31]:
s.shape

(4,)

### NaN(Not A Number)

In [32]:
s = pd.Series(person + [np.nan])
print(s)

0     kim
1     lee
2    park
3    hong
4     NaN
dtype: object


In [35]:
arr = np.arange(50,55)
s = pd.Series(arr, dtype='float')
print(s)

0    50.0
1    51.0
2    52.0
3    53.0
4    54.0
dtype: float64


In [37]:
f = ['바나나', np.nan, '사과', '포도', '복숭아']
s = pd.Series(f, index = list('가나다라마'))
print(s)

가    바나나
나    NaN
다     사과
라     포도
마    복숭아
dtype: object


## Fancy Indexing

In [39]:
s[['가', '나']]

가    바나나
나    NaN
dtype: object

In [41]:
s.iloc[[2,3]]
# s[['다', '라']]

다    사과
라    포도
dtype: object

## Boolean 으로 접근

In [42]:
s[[True, False, True, False, True]]

가    바나나
다     사과
마    복숭아
dtype: object

In [44]:
a = [True, False, False , True, True]
s[a]

가    바나나
라     포도
마    복숭아
dtype: object

In [48]:
arr = np.arange(5,20)
s = pd.Series(arr)
print(s)

s > 10

0      5
1      6
2      7
3      8
4      9
5     10
6     11
7     12
8     13
9     14
10    15
11    16
12    17
13    18
14    19
dtype: int64


0     False
1     False
2     False
3     False
4     False
5     False
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
dtype: bool

In [49]:
s[s > 10]

6     11
7     12
8     13
9     14
10    15
11    16
12    17
13    18
14    19
dtype: int64

In [50]:
s[s==5]

0    5
dtype: int64

## 결측치 처리

In [53]:
s[1:3]

1    5.0
2    2.0
dtype: float64

In [55]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [58]:
df = pd.DataFrame(arr)
df

0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

In [61]:
df = pd.DataFrame(arr, 
                  columns=['가', '나', '다'],
                 index = ['a', 'b', 'c']
                 )

df

가  나  다
a  0  1  2
b  3  4  5
c  6  7  8

In [86]:
data = {
    'name' : ['kim', 'lee', 'park'],
    'age' : [10, 15, 20],
    'location' : ['seoul', 'LA', 'tokyo']
}

df = pd.DataFrame(data)
df

name  age location
0   kim   10    seoul
1   lee   15       LA
2  park   20    tokyo

In [70]:
print(df.index)
print(df.columns)
print(df.values)
print(df.dtypes)

RangeIndex(start=0, stop=3, step=1)
Index(['name', 'age', 'location'], dtype='object')
[['kim' 10 'seoul']
 ['lee' 15 'LA']
 ['park' 20 'tokyo']]
name        object
age          int64
location    object
dtype: object


In [71]:
df.T

0    1      2
name        kim  lee   park
age          10   15     20
location  seoul   LA  tokyo

In [72]:
df.index = list('abc')
df

name  age location
a   kim   10    seoul
b   lee   15       LA
c  park   20    tokyo

### Column

In [87]:
print(df['name'])

0     kim
1     lee
2    park
Name: name, dtype: object


In [75]:
type(df['name'])

pandas.core.series.Series

In [76]:
df[['name', 'location']]

name location
a   kim    seoul
b   lee       LA
c  park    tokyo

In [89]:
df.rename(columns={'location' : 'hometown'}, inplace = True)
df

name  age hometown
0   kim   10    seoul
1   lee   15       LA
2  park   20    tokyo